name: 'honkit-publish'
description: 'Run make in a repository with honkit and calibre installed'
author: 'dariusf'
inputs:
  target:
    description: 'Target to make'
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
